name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubunty-latest
    steps:
       - name: Authenticate GitHub CLI
         run: gh auth login --with-token <<< "${{secret.GITHUB_TOKEN}}"
       - name: Post welcome comment
         run: gh pr comment ${{github.event.pull_request.html_url}} --body "Welcome to the repository!"
    
    
