name: Post welcome comment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # Step 2: Post a welcome comment on the pull request
      - name: Post welcome comment
        run: |
          gh pr comment ${{ github.event.pull_request.html_url }} --body "Welcome to the repository!"
